# Generated by Django 5.1 on 2024-08-10 06:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formsystem", "0002_courseform_signed_form"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseform",
            name="signed_form",
        ),
        migrations.CreateModel(
            name="SignedCourseForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("signed_form", models.FileField(upload_to="signed_course_forms/")),
                (
                    "course_form",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formsystem.courseform",
                    ),
                ),
            ],
        ),
    ]
